### ISSUE TITLE
Can't run project: NoClassDefFoundError

### ISSUE THREAD

**Issue by krlmlr** [falc-sim-org/FaLC#1]
Did the following (on Ubuntu 15.10), according to the README:

``` bash
git clone https://github.com/falc-sim-org/FaLC.git
cd FaLC
mvn package
java -Xms1G -Xmx4G -jar falc-sim-impl/target/falc-sim-impl-1.1.0.jar
```

The last command threw the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContext
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
    at java.lang.Class.getMethod0(Class.java:2866)
    at java.lang.Class.getMethod(Class.java:1676)
    at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContext
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 6 more
```

What am I missing?

**Comment by p-furtak** [comment]
Fixed copy dependences in falc-sim-impl.pom.xml

To run FALC properly, you should run it with project parameter like:

java -Xms1G -Xmx4G -jar falc-sim-impl/target/falc-sim-impl-1.1.0.jar -Dproject.name="path to project"

**Comment by krlmlr** [comment]
Thanks, fixed.
